apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: nirajvasani2204/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
    - image: nirajvasani2204/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: nirajvasani2204/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
    - image: nirajvasani2204/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
    - image: nirajvasani2204/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
    - image: nirajvasani2204/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
